version: '3.8'

services:
  graphdb:
    image: ontotext/graphdb:10.1.3
    container_name: graphdb-${ENVIRONMENT}
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx20g -Xms20g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Dgraphdb.global.page.cache=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    volumes:
      - graphdb-data:/opt/graphdb/home
    ports:
      - "7200:7200"


volumes:
  graphdb-data:
    name: graphdb-${ENVIRONMENT}


